### ISSUE TITLE
Why don't accept multiple types for ListTag ?

### ISSUE THREAD

**Issue by Elikill58** [GeyserMC/OpenNBT#20]
This is not really an issue but mostly a question. I don't understand why there is [this](https://github.com/GeyserMC/OpenNBT/blob/master/src/main/java/com/github/steveice10/opennbt/tag/builtin/ListTag.java#L107) because multiple list can have multiple types.

Also, if we use `setValue()`, it works. So: why ? Why throw error only with default value but not when replacing it ?

**Comment by RednedEpic** [comment]
A list tag in Minecraft only supports one type. You can’t have a string and byte tag for instance in the same nbt list.

In the future, please join our Discord server if you have any questions about the protocol / NBT. The issues section is more for reporting issues
